### PR TITLE
Fix compile errors, adding consts back

### LINKED ISSUE #41: Compile errors in master
Pulling master (@ 80e83b8) results in compile errors:

```
$ dep ensure
$ go build ./...
# github.com/cloudflare/cloudflare-ingress-controller/pkg/controller
pkg/controller/controller.go:53:61: undefined: Config
pkg/controller/controller.go:174:34: undefined: IngressClassKey
pkg/controller/controller.go:176:50: undefined: IngressClassKey
pkg/controller/controller.go:179:39: undefined: IngressClassKey
pkg/controller/controller.go:547:40: undefined: IngressAnnotationLBPool
pkg/controller/controller.go:560:20: undefined: SecretLabelDomain
pkg/controller/controller.go:568:79: undefined: SecretLabelDomain
pkg/controller/controller.go:573:88: undefined: SecretLabelDomain
pkg/controller/controller.go:573:117: undefined: SecretName
pkg/controller/controller.go:574:70: undefined: SecretName
pkg/controller/controller.go:574:70: too many errors
```

The same errors are present when running `go install`:

```
$ go install github.com/cloudflare/cloudflare-ingress-controller/cmd/argot
# github.com/cloudflare/cloudflare-ingress-controller/pkg/controller
pkg/controller/controller.go:53:61: undefined: Config
pkg/controller/controller.go:174:34: undefined: IngressClassKey
pkg/controller/controller.go:176:50: undefined: IngressClassKey
pkg/controller/controller.go:179:39: undefined: IngressClassKey
pkg/controller/controller.go:547:40: undefined: IngressAnnotationLBPool
pkg/controller/controller.go:560:20: undefined: SecretLabelDomain
pkg/controller/controller.go:568:79: undefined: SecretLabelDomain
pkg/controller/controller.go:573:88: undefined: SecretLabelDomain
pkg/controller/controller.go:573:117: undefined: SecretName
pkg/controller/controller.go:574:70: undefined: SecretName
pkg/controller/controller.go:574:70: too many errors
```

### PR DESCRIPTION
**Pull request by marccampbell**
Closes #41 

Master did not compile.  Running git bisect makes this appear to be a good candidate to resolve. Tests pass with this commit.

### CODE REVIEW

**Comment by mattalberts** [comment]
Hey @marccampbell1 Thanks for finding this!  I'm just getting ramped up (on the project); let me review and get back to you. My plan was to update documentation and setup travis ci first, but broken master is broken master

**Comment by ntfrnzn** [comment]
@mattalberts @marccampbell1 CI would be great, would help tell me that I moved ten lines into a separate configuration file and didn't add it to git.  Apologies, and thanks.

**Comment by mattalberts** [comment]
@ntfrnzn No worries!  It happens to us!   I'm working on getting CI setup now!
